services:

  postgres:
    image: postgres:16-alpine
    container_name: journeysync-postgres

    environment:
      POSTGRES_DB: travel_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - journeysync-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d travel_planner"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./Backend

    container_name: journeysync-backend

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel_planner
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - journeysync-network


  frontend:
    build:
      context: ./frontend

    container_name: journeysync-frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    networks:
      - journeysync-network


volumes:
  postgres_data:


networks:
  journeysync-network:
    driver: bridge
