apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: journeysync
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: journeysync-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/travel_planner

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: journeysync-secrets
                  key: postgres-password

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: journeysync-secrets
                  key: jwt-secret

            - name: JWT_EXPIRATION
              value: "86400000"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: journeysync

spec:
  selector:
    app: backend

  ports:
    - port: 8080
      targetPort: 8080

  type: ClusterIP
