name: JourneySync CD

on:
  workflow_run:
    workflows: ["JourneySync CI"]
    types:
      - completed
    branches:
      - DevOps-final

jobs:
  docker:
    name: Build and Push Docker Images
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: DevOps-final

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: |
            ghcr.io/sofi665/journeysync-backend:latest
            ghcr.io/sofi665/journeysync-backend:${{ github.event.workflow_run.head_sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=http://localhost:30080
          tags: |
            ghcr.io/sofi665/journeysync-frontend:latest
            ghcr.io/sofi665/journeysync-frontend:${{ github.event.workflow_run.head_sha }}
